#!/bin/bash

javadoc -private \
        -classpath lib/mysql-connector-java-5.1.6.jar:lib/commons-dbutils-1.3.jar:. \
        -d javadoc \
        src/com/kennyscott/serializingobjectstodatabase/*.java
